apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: harbor.blackgallina.cat/build-service/tbs/knote@sha256:6ac1a09615ebadd4ac2ce32cd2777c90e4f0a9a0df6a5e77b0516dbe241b628a
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo.sandbox:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 8080
